$: s('bd').euclid(3, 8).bank('tr909')

$: note('0 2 3 4'.scale('A minor'))
  .add(note('0,.20'))
  .add(note(perlin.range(0, 0.1)))
  .iter(4)
  .slow(4)
  .s('supersaw')
  .transpose(-24)
  .lpf(2500)
  .lpenv(8)
  .lpq(8)
  .distort(0.3)
  .delay(0.3)
  .room(1)
  ._punchcard({ labels: true })
$: n(run(3))
  .s('sleighbells*3')
  .clip(0.8)
  .room(1)
  .rsize(1.5)
  .delay(0.5)
  ._punchcard({ labels: true })

$: n(run(8)).s('cajon').delay(0.2)

$: n(run(8))
  .s('wt_digital_echoes')
  .chord('Am Em'.slow(2))
  .voicing()
  // .slow(2)
  .delay(0.8)
  .lpf(5000)
  .lpenv(2)
  .lpq(1)
  .clip(perlin.range(0.1, 0.9).fast(16))
  ._pianoroll()
$: n(run(8))
  .s('wt_digital_curses,saw,square')
  .chord('Am Em C G'.slow(2))
  .voicing()
  .euclid(4, 16)
  .sometimes((x) => x.add(note('0,.2')))
  .fast(2)
  .delay(0.8)
  .lpf(5000)
  .lpenv(8)
  .lpq(4)
  .pan('.25')
  // .clip(perlin.range(.1, .9).fast(16))
  .degradeBy(perlin.range(0.1, 0.25).fast(16))
  .room(2)
  .rsize(1.5)
  .postgain(0.7)
  ._pianoroll({
    labels: true,
  })
